<?php
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Exceptions;

use ThingSpaceConnectivityManagementAPILib\APIException;
use ThingSpaceConnectivityManagementAPILib\APIHelper;
/**
 * @todo Write general description for this model
 */
class RestErrorResponseException extends APIException{
    /**
     * @todo Write general description for this property
     * @var string $errorCode public property
     */
    public $errorCode;

    /**
     * @todo Write general description for this property
     * @var string $errorMessage public property
     */
    public $errorMessage;


    /**
    * Constructor to set initial or default values of member properties 
    */
    public function __construct($reason,$context)
    {
        parent::__construct($reason,$context);
    }

    public function unbox()
    {
        $data = APIHelper::deserialize(self::getResponseBody());
        $errorCode = $data['errorCode'];
        $errorMessage = $data['errorMessage'];
    }
}