<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class AddDevicesResponseMessage implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var DeviceId[] $deviceIds public property
     */
    public $deviceIds;

    /**
     * @todo Write general description for this property
     * @var string $response public property
     */
    public $response;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $deviceIds   Initialization value for the property $this->deviceIds
     * @param   string            $response    Initialization value for the property $this->response 
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->deviceIds = func_get_arg(0);
            $this->response  = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['deviceIds'] = $this->deviceIds;
        $json['response']  = $this->response;

        return $json;
    }
}