<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class AddDevicesRequest implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $accountName public property
     */
    public $accountName;

    /**
     * @todo Write general description for this property
     * @var KvPair[] $customFields public property
     */
    public $customFields;

    /**
     * @todo Write general description for this property
     * @var DeviceList[] $devicesToAdd public property
     */
    public $devicesToAdd;

    /**
     * @todo Write general description for this property
     * @var string $groupName public property
     */
    public $groupName;

    /**
     * @todo Write general description for this property
     * @var string $skuNumber public property
     */
    public $skuNumber;

    /**
     * @todo Write general description for this property
     * @var string $state public property
     */
    public $state;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $accountName    Initialization value for the property $this->accountName 
     * @param   array             $customFields   Initialization value for the property $this->customFields
     * @param   array             $devicesToAdd   Initialization value for the property $this->devicesToAdd
     * @param   string            $groupName      Initialization value for the property $this->groupName   
     * @param   string            $skuNumber      Initialization value for the property $this->skuNumber   
     * @param   string            $state          Initialization value for the property $this->state       
     */
    public function __construct()
    {
        if(6 == func_num_args())
        {
            $this->accountName  = func_get_arg(0);
            $this->customFields = func_get_arg(1);
            $this->devicesToAdd = func_get_arg(2);
            $this->groupName    = func_get_arg(3);
            $this->skuNumber    = func_get_arg(4);
            $this->state        = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['accountName']  = $this->accountName;
        $json['customFields'] = $this->customFields;
        $json['devicesToAdd'] = $this->devicesToAdd;
        $json['groupName']    = $this->groupName;
        $json['skuNumber']    = $this->skuNumber;
        $json['state']        = $this->state;

        return $json;
    }
}