<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Address implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $addressLine1 public property
     */
    public $addressLine1;

    /**
     * @todo Write general description for this property
     * @var string $addressLine2 public property
     */
    public $addressLine2;

    /**
     * @todo Write general description for this property
     * @var string $city public property
     */
    public $city;

    /**
     * @todo Write general description for this property
     * @var string $country public property
     */
    public $country;

    /**
     * @todo Write general description for this property
     * @var string $state public property
     */
    public $state;

    /**
     * @todo Write general description for this property
     * @var string $zip public property
     */
    public $zip;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $addressLine1   Initialization value for the property $this->addressLine1
     * @param   string            $addressLine2   Initialization value for the property $this->addressLine2
     * @param   string            $city           Initialization value for the property $this->city        
     * @param   string            $country        Initialization value for the property $this->country     
     * @param   string            $state          Initialization value for the property $this->state       
     * @param   string            $zip            Initialization value for the property $this->zip         
     */
    public function __construct()
    {
        if(6 == func_num_args())
        {
            $this->addressLine1 = func_get_arg(0);
            $this->addressLine2 = func_get_arg(1);
            $this->city         = func_get_arg(2);
            $this->country      = func_get_arg(3);
            $this->state        = func_get_arg(4);
            $this->zip          = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['addressLine1'] = $this->addressLine1;
        $json['addressLine2'] = $this->addressLine2;
        $json['city']         = $this->city;
        $json['country']      = $this->country;
        $json['state']        = $this->state;
        $json['zip']          = $this->zip;

        return $json;
    }
}