<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Callback implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $accountName public property
     */
    public $accountName;

    /**
     * @todo Write general description for this property
     * @var string $password public property
     */
    public $password;

    /**
     * @todo Write general description for this property
     * @var string $serviceName public property
     */
    public $serviceName;

    /**
     * @todo Write general description for this property
     * @var string $url public property
     */
    public $url;

    /**
     * @todo Write general description for this property
     * @var string $username public property
     */
    public $username;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $accountName   Initialization value for the property $this->accountName
     * @param   string            $password      Initialization value for the property $this->password   
     * @param   string            $serviceName   Initialization value for the property $this->serviceName
     * @param   string            $url           Initialization value for the property $this->url        
     * @param   string            $username      Initialization value for the property $this->username   
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->accountName = func_get_arg(0);
            $this->password    = func_get_arg(1);
            $this->serviceName = func_get_arg(2);
            $this->url         = func_get_arg(3);
            $this->username    = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['accountName'] = $this->accountName;
        $json['password']    = $this->password;
        $json['serviceName'] = $this->serviceName;
        $json['url']         = $this->url;
        $json['username']    = $this->username;

        return $json;
    }
}