<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CallbackActionResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $accountName public property
     */
    public $accountName;

    /**
     * @todo Write general description for this property
     * @var string $serviceName public property
     */
    public $serviceName;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $accountName   Initialization value for the property $this->accountName
     * @param   string            $serviceName   Initialization value for the property $this->serviceName
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->accountName = func_get_arg(0);
            $this->serviceName = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['accountName'] = $this->accountName;
        $json['serviceName'] = $this->serviceName;

        return $json;
    }
}