<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CarrierActivateRequest implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $accountName public property
     */
    public $accountName;

    /**
     * @todo Write general description for this property
     * @var string $carrierIpPoolName public property
     */
    public $carrierIpPoolName;

    /**
     * @todo Write general description for this property
     * @var string $carrierName public property
     */
    public $carrierName;

    /**
     * @todo Write general description for this property
     * @var string $costCenterCode public property
     */
    public $costCenterCode;

    /**
     * @todo Write general description for this property
     * @var KvPair[] $customFields public property
     */
    public $customFields;

    /**
     * @todo Write general description for this property
     * @var DeviceList[] $devices public property
     */
    public $devices;

    /**
     * @todo Write general description for this property
     * @var string $groupName public property
     */
    public $groupName;

    /**
     * @todo Write general description for this property
     * @var string $leadId public property
     */
    public $leadId;

    /**
     * @todo Write general description for this property
     * @var string $mdnZipCode public property
     */
    public $mdnZipCode;

    /**
     * @todo Write general description for this property
     * @var PlaceOfUse $primaryPlaceOfUse public property
     */
    public $primaryPlaceOfUse;

    /**
     * @todo Write general description for this property
     * @var string $publicIpRestriction public property
     */
    public $publicIpRestriction;

    /**
     * @todo Write general description for this property
     * @var string $servicePlan public property
     */
    public $servicePlan;

    /**
     * @todo Write general description for this property
     * @var string $skuNumber public property
     */
    public $skuNumber;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $accountName           Initialization value for the property $this->accountName        
     * @param   string            $carrierIpPoolName     Initialization value for the property $this->carrierIpPoolName  
     * @param   string            $carrierName           Initialization value for the property $this->carrierName        
     * @param   string            $costCenterCode        Initialization value for the property $this->costCenterCode     
     * @param   array             $customFields          Initialization value for the property $this->customFields       
     * @param   array             $devices               Initialization value for the property $this->devices            
     * @param   string            $groupName             Initialization value for the property $this->groupName          
     * @param   string            $leadId                Initialization value for the property $this->leadId             
     * @param   string            $mdnZipCode            Initialization value for the property $this->mdnZipCode         
     * @param   PlaceOfUse        $primaryPlaceOfUse     Initialization value for the property $this->primaryPlaceOfUse  
     * @param   string            $publicIpRestriction   Initialization value for the property $this->publicIpRestriction
     * @param   string            $servicePlan           Initialization value for the property $this->servicePlan        
     * @param   string            $skuNumber             Initialization value for the property $this->skuNumber          
     */
    public function __construct()
    {
        if(13 == func_num_args())
        {
            $this->accountName         = func_get_arg(0);
            $this->carrierIpPoolName   = func_get_arg(1);
            $this->carrierName         = func_get_arg(2);
            $this->costCenterCode      = func_get_arg(3);
            $this->customFields        = func_get_arg(4);
            $this->devices             = func_get_arg(5);
            $this->groupName           = func_get_arg(6);
            $this->leadId              = func_get_arg(7);
            $this->mdnZipCode          = func_get_arg(8);
            $this->primaryPlaceOfUse   = func_get_arg(9);
            $this->publicIpRestriction = func_get_arg(10);
            $this->servicePlan         = func_get_arg(11);
            $this->skuNumber           = func_get_arg(12);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['accountName']         = $this->accountName;
        $json['carrierIpPoolName']   = $this->carrierIpPoolName;
        $json['carrierName']         = $this->carrierName;
        $json['costCenterCode']      = $this->costCenterCode;
        $json['customFields']        = $this->customFields;
        $json['devices']             = $this->devices;
        $json['groupName']           = $this->groupName;
        $json['leadId']              = $this->leadId;
        $json['mdnZipCode']          = $this->mdnZipCode;
        $json['primaryPlaceOfUse']   = $this->primaryPlaceOfUse;
        $json['publicIpRestriction'] = $this->publicIpRestriction;
        $json['servicePlan']         = $this->servicePlan;
        $json['skuNumber']           = $this->skuNumber;

        return $json;
    }
}