<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class CarrierInformation implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $carrierName public property
     */
    public $carrierName;

    /**
     * @todo Write general description for this property
     * @var string $servicePlan public property
     */
    public $servicePlan;

    /**
     * @todo Write general description for this property
     * @var string $state public property
     */
    public $state;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $carrierName   Initialization value for the property $this->carrierName
     * @param   string            $servicePlan   Initialization value for the property $this->servicePlan
     * @param   string            $state         Initialization value for the property $this->state      
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->carrierName = func_get_arg(0);
            $this->servicePlan = func_get_arg(1);
            $this->state       = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['carrierName'] = $this->carrierName;
        $json['servicePlan'] = $this->servicePlan;
        $json['state']       = $this->state;

        return $json;
    }
}