<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ConnectionEvent implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var KvPair[] $connectionEventAttributes public property
     */
    public $connectionEventAttributes;

    /**
     * @todo Write general description for this property
     * @var KvPair[] $extendedAttributes public property
     */
    public $extendedAttributes;

    /**
     * @todo Write general description for this property
     * @var string $occurredAt public property
     */
    public $occurredAt;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $connectionEventAttributes   Initialization value for the property $this->connectionEventAttributes
     * @param   array             $extendedAttributes          Initialization value for the property $this->extendedAttributes       
     * @param   string            $occurredAt                  Initialization value for the property $this->occurredAt               
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->connectionEventAttributes = func_get_arg(0);
            $this->extendedAttributes        = func_get_arg(1);
            $this->occurredAt                = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['connectionEventAttributes'] = $this->connectionEventAttributes;
        $json['extendedAttributes']        = $this->extendedAttributes;
        $json['occurredAt']                = $this->occurredAt;

        return $json;
    }
}