<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class DeviceAggregateUsageListRequest implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $accountName public property
     */
    public $accountName;

    /**
     * @todo Write general description for this property
     * @var DeviceId[] $deviceIds public property
     */
    public $deviceIds;

    /**
     * @todo Write general description for this property
     * @var string $endTime public property
     */
    public $endTime;

    /**
     * @todo Write general description for this property
     * @var string $groupName public property
     */
    public $groupName;

    /**
     * @todo Write general description for this property
     * @var string $startTime public property
     */
    public $startTime;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $accountName   Initialization value for the property $this->accountName
     * @param   array             $deviceIds     Initialization value for the property $this->deviceIds  
     * @param   string            $endTime       Initialization value for the property $this->endTime    
     * @param   string            $groupName     Initialization value for the property $this->groupName  
     * @param   string            $startTime     Initialization value for the property $this->startTime  
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->accountName = func_get_arg(0);
            $this->deviceIds   = func_get_arg(1);
            $this->endTime     = func_get_arg(2);
            $this->groupName   = func_get_arg(3);
            $this->startTime   = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['accountName'] = $this->accountName;
        $json['deviceIds']   = $this->deviceIds;
        $json['endTime']     = $this->endTime;
        $json['groupName']   = $this->groupName;
        $json['startTime']   = $this->startTime;

        return $json;
    }
}