<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Device implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $accountName public property
     */
    public $accountName;

    /**
     * @todo Write general description for this property
     * @var string $billingCycleEndDate public property
     */
    public $billingCycleEndDate;

    /**
     * @todo Write general description for this property
     * @var CarrierInformation[] $carrierInformations public property
     */
    public $carrierInformations;

    /**
     * @todo Write general description for this property
     * @var bool $connected public property
     */
    public $connected;

    /**
     * @todo Write general description for this property
     * @var string $createdAt public property
     */
    public $createdAt;

    /**
     * @todo Write general description for this property
     * @var KvPair[] $customFields public property
     */
    public $customFields;

    /**
     * @todo Write general description for this property
     * @var DeviceId[] $deviceIds public property
     */
    public $deviceIds;

    /**
     * @todo Write general description for this property
     * @var KvPair[] $extendedAttributes public property
     */
    public $extendedAttributes;

    /**
     * @todo Write general description for this property
     * @var array $groupNames public property
     */
    public $groupNames;

    /**
     * @todo Write general description for this property
     * @var string $ipAddress public property
     */
    public $ipAddress;

    /**
     * @todo Write general description for this property
     * @var string $lastActivationBy public property
     */
    public $lastActivationBy;

    /**
     * @todo Write general description for this property
     * @var string $lastActivationDate public property
     */
    public $lastActivationDate;

    /**
     * @todo Write general description for this property
     * @var string $lastConnectionDate public property
     */
    public $lastConnectionDate;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $accountName           Initialization value for the property $this->accountName        
     * @param   string            $billingCycleEndDate   Initialization value for the property $this->billingCycleEndDate
     * @param   array             $carrierInformations   Initialization value for the property $this->carrierInformations
     * @param   bool              $connected             Initialization value for the property $this->connected          
     * @param   string            $createdAt             Initialization value for the property $this->createdAt          
     * @param   array             $customFields          Initialization value for the property $this->customFields       
     * @param   array             $deviceIds             Initialization value for the property $this->deviceIds          
     * @param   array             $extendedAttributes    Initialization value for the property $this->extendedAttributes 
     * @param   array             $groupNames            Initialization value for the property $this->groupNames         
     * @param   string            $ipAddress             Initialization value for the property $this->ipAddress          
     * @param   string            $lastActivationBy      Initialization value for the property $this->lastActivationBy   
     * @param   string            $lastActivationDate    Initialization value for the property $this->lastActivationDate 
     * @param   string            $lastConnectionDate    Initialization value for the property $this->lastConnectionDate 
     */
    public function __construct()
    {
        if(13 == func_num_args())
        {
            $this->accountName         = func_get_arg(0);
            $this->billingCycleEndDate = func_get_arg(1);
            $this->carrierInformations = func_get_arg(2);
            $this->connected           = func_get_arg(3);
            $this->createdAt           = func_get_arg(4);
            $this->customFields        = func_get_arg(5);
            $this->deviceIds           = func_get_arg(6);
            $this->extendedAttributes  = func_get_arg(7);
            $this->groupNames          = func_get_arg(8);
            $this->ipAddress           = func_get_arg(9);
            $this->lastActivationBy    = func_get_arg(10);
            $this->lastActivationDate  = func_get_arg(11);
            $this->lastConnectionDate  = func_get_arg(12);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['accountName']         = $this->accountName;
        $json['billingCycleEndDate'] = $this->billingCycleEndDate;
        $json['carrierInformations'] = $this->carrierInformations;
        $json['connected']           = $this->connected;
        $json['createdAt']           = $this->createdAt;
        $json['customFields']        = $this->customFields;
        $json['deviceIds']           = $this->deviceIds;
        $json['extendedAttributes']  = $this->extendedAttributes;
        $json['groupNames']          = $this->groupNames;
        $json['ipAddress']           = $this->ipAddress;
        $json['lastActivationBy']    = $this->lastActivationBy;
        $json['lastActivationDate']  = $this->lastActivationDate;
        $json['lastConnectionDate']  = $this->lastConnectionDate;

        return $json;
    }
}