<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class DeviceList implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var DeviceId[] $deviceIds public property
     */
    public $deviceIds;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $deviceIds   Initialization value for the property $this->deviceIds
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->deviceIds = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['deviceIds'] = $this->deviceIds;

        return $json;
    }
}