<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class DeviceProvisioningHistoryListRequest implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var DeviceId $deviceId public property
     */
    public $deviceId;

    /**
     * @todo Write general description for this property
     * @var string $earliest public property
     */
    public $earliest;

    /**
     * @todo Write general description for this property
     * @var string $latest public property
     */
    public $latest;

    /**
     * Constructor to set initial or default values of member properties
     * @param   DeviceId          $deviceId   Initialization value for the property $this->deviceId
     * @param   string            $earliest   Initialization value for the property $this->earliest
     * @param   string            $latest     Initialization value for the property $this->latest  
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->deviceId = func_get_arg(0);
            $this->earliest = func_get_arg(1);
            $this->latest   = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['deviceId'] = $this->deviceId;
        $json['earliest'] = $this->earliest;
        $json['latest']   = $this->latest;

        return $json;
    }
}