<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class DeviceId implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @var string $kind public property
     */
    public $kind;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $id     Initialization value for the property $this->id  
     * @param   string            $kind   Initialization value for the property $this->kind
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->id   = func_get_arg(0);
            $this->kind = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']   = $this->id;
        $json['kind'] = $this->kind;

        return $json;
    }
}