<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class GroupUpdateRequest implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var DeviceId[] $devicesToAdd public property
     */
    public $devicesToAdd;

    /**
     * @todo Write general description for this property
     * @var DeviceId[] $devicesToRemove public property
     */
    public $devicesToRemove;

    /**
     * @todo Write general description for this property
     * @var string $newGroupDescription public property
     */
    public $newGroupDescription;

    /**
     * @todo Write general description for this property
     * @var string $newGroupName public property
     */
    public $newGroupName;

    /**
     * Constructor to set initial or default values of member properties
     * @param   array             $devicesToAdd          Initialization value for the property $this->devicesToAdd       
     * @param   array             $devicesToRemove       Initialization value for the property $this->devicesToRemove    
     * @param   string            $newGroupDescription   Initialization value for the property $this->newGroupDescription
     * @param   string            $newGroupName          Initialization value for the property $this->newGroupName       
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->devicesToAdd        = func_get_arg(0);
            $this->devicesToRemove     = func_get_arg(1);
            $this->newGroupDescription = func_get_arg(2);
            $this->newGroupName        = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['devicesToAdd']        = $this->devicesToAdd;
        $json['devicesToRemove']     = $this->devicesToRemove;
        $json['newGroupDescription'] = $this->newGroupDescription;
        $json['newGroupName']        = $this->newGroupName;

        return $json;
    }
}