<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class GroupResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $description public property
     */
    public $description;

    /**
     * @todo Write general description for this property
     * @var KvPair[] $extendedAttributes public property
     */
    public $extendedAttributes;

    /**
     * @todo Write general description for this property
     * @var bool $isDefaultGroup public property
     */
    public $isDefaultGroup;

    /**
     * @todo Write general description for this property
     * @var string $name public property
     */
    public $name;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $description          Initialization value for the property $this->description       
     * @param   array             $extendedAttributes   Initialization value for the property $this->extendedAttributes
     * @param   bool              $isDefaultGroup       Initialization value for the property $this->isDefaultGroup    
     * @param   string            $name                 Initialization value for the property $this->name              
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->description        = func_get_arg(0);
            $this->extendedAttributes = func_get_arg(1);
            $this->isDefaultGroup     = func_get_arg(2);
            $this->name               = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['description']        = $this->description;
        $json['extendedAttributes'] = $this->extendedAttributes;
        $json['isDefaultGroup']     = $this->isDefaultGroup;
        $json['name']               = $this->name;

        return $json;
    }
}