<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class GroupListResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $description public property
     */
    public $description;

    /**
     * @todo Write general description for this property
     * @var DeviceList[] $devices public property
     */
    public $devices;

    /**
     * @todo Write general description for this property
     * @var bool $hasMoreData public property
     */
    public $hasMoreData;

    /**
     * @todo Write general description for this property
     * @var string $name public property
     */
    public $name;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $description   Initialization value for the property $this->description
     * @param   array             $devices       Initialization value for the property $this->devices    
     * @param   bool              $hasMoreData   Initialization value for the property $this->hasMoreData
     * @param   string            $name          Initialization value for the property $this->name       
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->description = func_get_arg(0);
            $this->devices     = func_get_arg(1);
            $this->hasMoreData = func_get_arg(2);
            $this->name        = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['description'] = $this->description;
        $json['devices']     = $this->devices;
        $json['hasMoreData'] = $this->hasMoreData;
        $json['name']        = $this->name;

        return $json;
    }
}