<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class KvPair implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $key public property
     */
    public $key;

    /**
     * @todo Write general description for this property
     * @var string $value public property
     */
    public $value;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $key     Initialization value for the property $this->key  
     * @param   string            $value   Initialization value for the property $this->value
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->key   = func_get_arg(0);
            $this->value = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['key']   = $this->key;
        $json['value'] = $this->value;

        return $json;
    }
}