<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class PlaceOfUse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var Address $address public property
     */
    public $address;

    /**
     * @todo Write general description for this property
     * @var CustomerName $customerName public property
     */
    public $customerName;

    /**
     * Constructor to set initial or default values of member properties
     * @param   Address           $address        Initialization value for the property $this->address     
     * @param   CustomerName      $customerName   Initialization value for the property $this->customerName
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->address      = func_get_arg(0);
            $this->customerName = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['address']      = $this->address;
        $json['customerName'] = $this->customerName;

        return $json;
    }
}