<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ProvisioningHistory implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $eventBy public property
     */
    public $eventBy;

    /**
     * @todo Write general description for this property
     * @var string $eventType public property
     */
    public $eventType;

    /**
     * @todo Write general description for this property
     * @var KvPair[] $extendedAttributes public property
     */
    public $extendedAttributes;

    /**
     * @todo Write general description for this property
     * @var string $mdn public property
     */
    public $mdn;

    /**
     * @todo Write general description for this property
     * @var string $msisdn public property
     */
    public $msisdn;

    /**
     * @todo Write general description for this property
     * @var string $occurredAt public property
     */
    public $occurredAt;

    /**
     * @todo Write general description for this property
     * @var string $servicePlan public property
     */
    public $servicePlan;

    /**
     * @todo Write general description for this property
     * @var string $status public property
     */
    public $status;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $eventBy              Initialization value for the property $this->eventBy           
     * @param   string            $eventType            Initialization value for the property $this->eventType         
     * @param   array             $extendedAttributes   Initialization value for the property $this->extendedAttributes
     * @param   string            $mdn                  Initialization value for the property $this->mdn               
     * @param   string            $msisdn               Initialization value for the property $this->msisdn            
     * @param   string            $occurredAt           Initialization value for the property $this->occurredAt        
     * @param   string            $servicePlan          Initialization value for the property $this->servicePlan       
     * @param   string            $status               Initialization value for the property $this->status            
     */
    public function __construct()
    {
        if(8 == func_num_args())
        {
            $this->eventBy            = func_get_arg(0);
            $this->eventType          = func_get_arg(1);
            $this->extendedAttributes = func_get_arg(2);
            $this->mdn                = func_get_arg(3);
            $this->msisdn             = func_get_arg(4);
            $this->occurredAt         = func_get_arg(5);
            $this->servicePlan        = func_get_arg(6);
            $this->status             = func_get_arg(7);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['eventBy']            = $this->eventBy;
        $json['eventType']          = $this->eventType;
        $json['extendedAttributes'] = $this->extendedAttributes;
        $json['mdn']                = $this->mdn;
        $json['msisdn']             = $this->msisdn;
        $json['occurredAt']         = $this->occurredAt;
        $json['servicePlan']        = $this->servicePlan;
        $json['status']             = $this->status;

        return $json;
    }
}