<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class RegisterCallbackRequest implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @var string $url public property
     */
    public $url;

    /**
     * @todo Write general description for this property
     * @var string $username public property
     */
    public $username;

    /**
     * @todo Write general description for this property
     * @var string $password public property
     */
    public $password;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name       Initialization value for the property $this->name    
     * @param   string            $url        Initialization value for the property $this->url     
     * @param   string            $username   Initialization value for the property $this->username
     * @param   string            $password   Initialization value for the property $this->password
     */
    public function __construct()
    {
        if(4 == func_num_args())
        {
            $this->name     = func_get_arg(0);
            $this->url      = func_get_arg(1);
            $this->username = func_get_arg(2);
            $this->password = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']     = $this->name;
        $json['url']      = $this->url;
        $json['username'] = $this->username;
        $json['password'] = $this->password;

        return $json;
    }
}