<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class RequestResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $requestId public property
     */
    public $requestId;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $requestId   Initialization value for the property $this->requestId
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->requestId = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['requestId'] = $this->requestId;

        return $json;
    }
}