<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class RestSuccessResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var bool $success public property
     */
    public $success;

    /**
     * Constructor to set initial or default values of member properties
     * @param   bool              $success   Initialization value for the property $this->success
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->success = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['success'] = $this->success;

        return $json;
    }
}