<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class ServicePlanResponse implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $carrierServicePlanCode public property
     */
    public $carrierServicePlanCode;

    /**
     * @todo Write general description for this property
     * @var string $code public property
     */
    public $code;

    /**
     * @todo Write general description for this property
     * @var KvPair[] $extendedAttributes public property
     */
    public $extendedAttributes;

    /**
     * @todo Write general description for this property
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @var integer $sizeKb public property
     */
    public $sizeKb;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $carrierServicePlanCode   Initialization value for the property $this->carrierServicePlanCode
     * @param   string            $code                     Initialization value for the property $this->code                  
     * @param   array             $extendedAttributes       Initialization value for the property $this->extendedAttributes    
     * @param   string            $name                     Initialization value for the property $this->name                  
     * @param   integer           $sizeKb                   Initialization value for the property $this->sizeKb                
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->carrierServicePlanCode = func_get_arg(0);
            $this->code                   = func_get_arg(1);
            $this->extendedAttributes     = func_get_arg(2);
            $this->name                   = func_get_arg(3);
            $this->sizeKb                 = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['carrierServicePlanCode'] = $this->carrierServicePlanCode;
        $json['code']                   = $this->code;
        $json['extendedAttributes']     = $this->extendedAttributes;
        $json['name']                   = $this->name;
        $json['sizeKb']                 = $this->sizeKb;

        return $json;
    }
}