<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class SessionResetPasswordRequest implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var string $oldPassword public property
     */
    public $oldPassword;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $oldPassword   Initialization value for the property $this->oldPassword
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->oldPassword = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['oldPassword'] = $this->oldPassword;

        return $json;
    }
}