<?php 
/*
 * ThingSpaceConnectivityManagementAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 10/05/2016
 */

namespace ThingSpaceConnectivityManagementAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Usage implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @var integer $bytesUsed public property
     */
    public $bytesUsed;

    /**
     * @todo Write general description for this property
     * @var KvPair[] $extendedAttributes public property
     */
    public $extendedAttributes;

    /**
     * @todo Write general description for this property
     * @var string $servicePlan public property
     */
    public $servicePlan;

    /**
     * @todo Write general description for this property
     * @var integer $smsUsed public property
     */
    public $smsUsed;

    /**
     * @todo Write general description for this property
     * @var string $source public property
     */
    public $source;

    /**
     * @todo Write general description for this property
     * @var string $timestamp public property
     */
    public $timestamp;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $bytesUsed            Initialization value for the property $this->bytesUsed         
     * @param   array             $extendedAttributes   Initialization value for the property $this->extendedAttributes
     * @param   string            $servicePlan          Initialization value for the property $this->servicePlan       
     * @param   integer           $smsUsed              Initialization value for the property $this->smsUsed           
     * @param   string            $source               Initialization value for the property $this->source            
     * @param   string            $timestamp            Initialization value for the property $this->timestamp         
     */
    public function __construct()
    {
        if(6 == func_num_args())
        {
            $this->bytesUsed          = func_get_arg(0);
            $this->extendedAttributes = func_get_arg(1);
            $this->servicePlan        = func_get_arg(2);
            $this->smsUsed            = func_get_arg(3);
            $this->source             = func_get_arg(4);
            $this->timestamp          = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['bytesUsed']          = $this->bytesUsed;
        $json['extendedAttributes'] = $this->extendedAttributes;
        $json['servicePlan']        = $this->servicePlan;
        $json['smsUsed']            = $this->smsUsed;
        $json['source']             = $this->source;
        $json['timestamp']          = $this->timestamp;

        return $json;
    }
}